name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, x86_64-linux]
    steps:
      - uses: actions/checkout@v4
      - run: nix build --print-build-logs
      - run: nix run . | tee /tmp/out
      - run: grep "Hello, World!" /tmp/out
