name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: x86_64-linux
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: just ci
